linear_vel_pid:
  x:
    kp: 1000.0
    ki: 100.0
    kd: 2.0
    error_sum_tol: 0.4
    decay_rate: 0.1
    dead_zone_limit: 0.001
    lp_filter_alpha: 0.02
    saturation_limit: 30.0
  y:
    kp: 1000.0
    ki: 100.0
    kd: 2.0
    error_sum_tol: 0.4
    decay_rate: 0.1
    dead_zone_limit: 0.001
    lp_filter_alpha: 0.02
    saturation_limit: 30.0
  z:
    kp: 1200.0
    ki: 100.0
    kd: 2.0
    error_sum_tol: 0.4
    decay_rate: 0.1
    dead_zone_limit: 0.001
    lp_filter_alpha: 0.02
    saturation_limit: 30.0

orientation_ctrl:
  x:
    kp: 25.0
    ki: 0.0
    kd: 0.0
    error_sum_tol: 0.7
    decay_rate: 0.9
    dead_zone_limit: 0.05
    lp_filter_alpha: 0.01
    saturation_limit: 15.0
  y:
    kp: 25.0
    ki: 0.0
    kd: 0.0
    error_sum_tol: 0.7
    decay_rate: 0.9
    dead_zone_limit: 0.05
    lp_filter_alpha: 0.01
    saturation_limit: 15.0
  z:
    kp: 25.0
    ki: 0.0
    kd: 0.0
    error_sum_tol: 0.7
    decay_rate: 0.9
    dead_zone_limit: 0.05
    lp_filter_alpha: 0.01
    saturation_limit: 15.0